"""empty message

Revision ID: 179fe1a5635c
Revises: 41bac5a54ad4
Create Date: 2024-10-16 15:25:41.364992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179fe1a5635c'
down_revision = '41bac5a54ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
