"""empty message

Revision ID: 2f7aad697056
Revises: ba8ba243acc9
Create Date: 2024-10-17 21:54:42.050568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7aad697056'
down_revision = 'ba8ba243acc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'albums', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.drop_column('albums', 'artist_id')
    # ### end Alembic commands ###
