"""empty message

Revision ID: ba8ba243acc9
Revises: 
Create Date: 2024-10-17 21:32:37.019823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba8ba243acc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('songs', sa.ARRAY(sa.String()), nullable=False))
    op.drop_column('albums', 'songs_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('songs_name', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('albums', 'songs')
    # ### end Alembic commands ###
