"""empty message

Revision ID: ea7ac8ef324d
Revises: 8cb23a9218f3
Create Date: 2024-10-19 13:21:58.952049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea7ac8ef324d'
down_revision = '8cb23a9218f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('albums', 'album_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('albums', 'album_cover_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('albums', 'songs',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('albums', 'songs',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('albums', 'album_cover_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('albums', 'album_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
