"""empty message

Revision ID: ef602957fbc8
Revises: 
Create Date: 2024-10-15 23:43:40.083564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef602957fbc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('start_time', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
